// int TYPE_REWARD = 5;
// int TYPE_STRING = 1;
// int TYPE_TWODOUBLES = 2;
// int TYPE_ARRAY = 3;
// int TYPE_DOUBLEANDARRAY = 4;

int TYPE_REQUEST = 1;
int TYPE_REWARD = 2;
int TYPE_SEED = 3;
int TYPE_EMPTY_SEED = 4;
